<a href="https://colab.research.google.com/github/naveen959/Goeduhub/blob/main/Task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Task 4**
**Name - T. Naveen**

**Reg no. - 13234**

Q1. Import the numpy package under the name np and Print the numpy version and the configuration

In [19]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


Q2. Create a null vector of size 10

In [ ]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Q3. Create Simple 1-D array and check type and check data types in array

In [ ]:
a = np.array([10,20,30])
print(a)
print(a.dtype)

[10 20 30]
int64


Q4. How to find number of dimensions, bytes per element and bytes of memory used?

In [ ]:
import sys
y = np.array([1,2,3,4,5,6])
print('Dimension of array is: ',y.size)
print('Bytes per element is: ',y.itemsize)
print('Bytes of memory used: ',y.nbytes)

Dimension of array is:  6
Bytes per element is:  8
Bytes of memory used:  48


Q5. Create a null vector of size 10 but the fifth value which is 1

In [ ]:
x = np.zeros(10)
print(x)
print('Update fifth value to 1')
x[5]=1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


Q6. Create a vector with values ranging from 10 to 49

In [ ]:
z = np.arange(10,49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


Q7. Reverse a vector (first element becomes last)

In [ ]:
m = np.arange(0,10)
print('Original vector: ',m)
m = m[::-1]
print('Reverse vector: ',m)


Original vector:  [0 1 2 3 4 5 6 7 8 9]
Reverse vector:  [9 8 7 6 5 4 3 2 1 0]


Q8. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
t = np.arange(0,9).reshape(3,3)
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Q9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
n = [1,2,0,0,4,0]
print('Indices of non-zero elements are: ',np.nonzero(n))

Indices of non-zero elements are:  (array([0, 1, 4]),)


Q10. Create a 3x3 identity matrix

In [ ]:
i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q11. Create a 3x3x3 array with random values

In [ ]:
x = np.random.random((3,3,3))
print(x)

[[[0.67444679 0.53401142 0.95634293]
  [0.12295371 0.97642316 0.65040927]
  [0.21241406 0.44176028 0.61371857]]

 [[0.78978281 0.37815179 0.1432698 ]
  [0.2428302  0.07639738 0.08397845]
  [0.11181601 0.74692441 0.6618957 ]]

 [[0.04545506 0.15217793 0.79499799]
  [0.56934415 0.03209348 0.96384397]
  [0.30131136 0.71422179 0.5170828 ]]]


Q12. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
x = np.random.random((10,10))
print(x)
print('Minimum value of the array is: ',x.min())
print('Maximum value of the array is: ',x.max())

[[0.72244916 0.3467921  0.74900771 0.03703617 0.52316587 0.72262823
  0.42365423 0.61415316 0.82480851 0.5522736 ]
 [0.1273572  0.09657879 0.52557708 0.23863932 0.77263195 0.10436611
  0.44989451 0.99349537 0.19489206 0.99294653]
 [0.38319727 0.60457786 0.00347197 0.61318497 0.92670466 0.46087431
  0.93548741 0.24581587 0.09546181 0.96167831]
 [0.83712999 0.76287097 0.58239132 0.72144447 0.53945925 0.24682436
  0.15449973 0.03420439 0.66837518 0.2867181 ]
 [0.15424893 0.83190404 0.70160657 0.0668327  0.7329475  0.58485354
  0.13866293 0.88787672 0.59123464 0.6766245 ]
 [0.65973556 0.6741687  0.35505195 0.41669345 0.7542313  0.28820702
  0.47422946 0.23356289 0.20768989 0.32986925]
 [0.38796359 0.55095106 0.62425384 0.55320801 0.87304295 0.13466105
  0.04213091 0.23371094 0.79519711 0.9591317 ]
 [0.97768142 0.09995244 0.56475988 0.18506429 0.45542875 0.00317049
  0.58282117 0.79185834 0.03464358 0.79836859]
 [0.72279471 0.30611311 0.32134976 0.38958734 0.81957804 0.25799167
  0.10207552

Q13. Create a random vector of size 30 and find the mean value

In [ ]:
x = np.random.random((10))
print(x)
print('Mean value of the random vector is: ',x.mean())

[0.14716427 0.0469672  0.95270729 0.6818844  0.4278724  0.34337106
 0.59689842 0.55348202 0.40528306 0.12569328]
Mean value of the random vector is:  0.4281323415116196


Q14. Create a 2d array with 1 on the border and 0 inside

In [ ]:
x = np.ones((7,7))
print('Original array: ')
print(x)
x[1:-1,1:-1]=0
print('2d array with 1 on the border and 0 inside: ')
print(x)

Original array: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
2d array with 1 on the border and 0 inside: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


Q15. How to add a border (filled with 0's) around an existing array? 

In [ ]:
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


Q16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [43]:
a = np.arange(1,15).reshape(2,7)
print(a)

#Get 13
print(a[1,5])

#Get first row only
print(a[0])

#Get 3rd column only
print(a[:,2])

#Get [2,4,6]
print([a[0,1],a[0,3],a[0,5]])

#Replace 13 by 20
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[1 2 3 4 5 6 7]
[ 3 10]
[2, 4, 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


Q17. How to Convert a 1D array to a 2D array with 2 rows?

In [54]:
a = np.arange(10)
print('1D array:')
print(a)
a = a.reshape(2,5)
print('2D array with 2 rows:')
print(a)

1D array:
[0 1 2 3 4 5 6 7 8 9]
2D array with 2 rows:
[[0 1 2 3 4]
 [5 6 7 8 9]]


Q18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [55]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q19. Write a program to show how Numpy taking less memory compared to Python List?

In [58]:
import sys

l = range(100)
print('Size of each element of list in bytes: ',sys.getsizeof(l))
print('Size of the whole list in bytes: ',sys.getsizeof(l)*len(l))

a = np.arange(100)
print('Size of each element in the Numpy array in bytes: ',a.itemsize)
print('Size of the whole Numpy array in bites: ',a.itemsize*a.size)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  4800
Size of each element in the Numpy array in bytes:  8
Size of the whole Numpy array in bites:  800


Q20. Write a program to show how Numpy taking less time compared to Python List?

In [61]:
import sys
import time

size = 1000000
l1 = range(size)
l2 = range(size)

n1 = np.arange(size)
n2 = np.arange(size)

#list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print('Time taken by lists:')
print((time.time()-start)*1000)

#numpy array
start = time.time()
result1 = n1+n2
print('Time taken by numpy arrays')
print((time.time()-start)*1000)

Time taken by lists:
132.27367401123047
Time taken by numpy arrays
2.858877182006836
